class Labels:
    def __init__(self):
        self.labels_data = [
                {"id": 1, "label": "amanita_citrina", "translation": "Muchomor cytrynowy"},
                {"id": 2, "label": "cerioporus_squamosus", "translation": "Żagwiak łuskowaty"},
                {"id": 3, "label": "crucibulum_laeve", "translation": "Kubecznik pospolity"},
                {"id": 4, "label": "gyromitra_infula", "translation": "Piestrzenica infułowata"},
                {"id": 5, "label": "leccinum_albostipitatum", "translation": "Koźlarz białotrzonowy"},
                {"id": 6, "label": "paxillus_involutus", "translation": "Krowiak podwinięty"},
                {"id": 7, "label": "pleurotus_pulmonarius", "translation": "Boczniak łyżkowaty"},
                {"id": 8, "label": "trametes_ochracea", "translation": "Wrośniak strefowany"},
                {"id": 9, "label": "amanita_muscaria", "translation": "Muchomor czerwony"},
                {"id": 10, "label": "cetraria_islandica", "translation": "Płucnica islandzka"},
                {"id": 11, "label": "daedaleopsis_confragosa", "translation": "Gmatwica chropowata"},
                {"id": 12, "label": "hericium_coralloides", "translation": "Soplówka bukowa"},
                {"id": 13, "label": "leccinum_aurantiacum", "translation": "Koźlarz czerwony"},
                {"id": 14, "label": "peltigera_aphthosa", "translation": "Pawężnica brodawkowata"},
                {"id": 15, "label": "pseudevernia_furfuracea", "translation": "Mąklik otrębiasty"},
                {"id": 16, "label": "trametes_versicolor", "translation": "Wrośniak różnobarwny"},
                {"id": 17, "label": "amanita_pantherina", "translation": "Muchomor plamisty"},
                {"id": 18, "label": "chlorociboria_aeruginascens", "translation": "Chlorówka drobna"},
                {"id": 19, "label": "daedaleopsis_tricolor", "translation": "Gmatwica trójbarwna"},
                {"id": 20, "label": "hygrophoropsis_aurantiaca", "translation": "Lisówka pomarańczowa"},
                {"id": 21, "label": "leccinum_scabrum", "translation": "Koźlarz babka"},
                {"id": 22, "label": "peltigera_praetextata", "translation": "Pawężnica łuseczkowata"},
                {"id": 23, "label": "rhytisma_acerinum", "translation": "Łuszczeniec klonowy"},
                {"id": 24, "label": "tremella_mesenterica", "translation": "Trzęsak pomarańczowożółty"},
                {"id": 25, "label": "amanita_rubescens", "translation": "Muchomor czerwieniejący"},
                {"id": 26, "label": "chondrostereum_purpureum", "translation": "Chrząstkoskórnik purpurowy"},
                {"id": 27, "label": "evernia_mesomorpha", "translation": "Evernia"},
                {"id": 28, "label": "hypholoma_fasciculare", "translation": "Maślanka wiązkowa"},
                {"id": 29, "label": "leccinum_versipelle", "translation": "Koźlarz pomarańczowożółty"},
                {"id": 30, "label": "phaeophyscia_orbicularis", "translation": "Orzast kolisty"},
                {"id": 31, "label": "sarcomyxa_serotina", "translation": "Łycznik późny"},
                {"id": 32, "label": "trichaptum_biforme", "translation": "Trichaptum"},
                {"id": 33, "label": "apioperdon_pyriforme", "translation": "Purchawka gruszkowata"},
                {"id": 34, "label": "cladonia_fimbriata", "translation": "Chrobotek strzępiasty"},
                {"id": 35, "label": "evernia_prunastri", "translation": "Mąkla tarniowa"},
                {"id": 36, "label": "hypholoma_lateritium", "translation": "Maślanka ceglasta"},
                {"id": 37, "label": "lepista_nuda", "translation": "Gąsówka fioletowawa"},
                {"id": 38, "label": "phallus_impudicus", "translation": "Sromotnik smrodliwy"},
                {"id": 39, "label": "sarcoscypha_austriaca", "translation": "Czarka austriacka"},
                {"id": 40, "label": "tricholomopsis_rutilans", "translation": "Rycerzyk czerwonozłoty"},
                {"id": 41, "label": "armillaria_borealis", "translation": "Opieńka północna"},
                {"id": 42, "label": "cladonia_rangiferina", "translation": "Chrobotek reniferowy"},
                {"id": 43, "label": "flammulina_velutipes", "translation": "Flammulina"},
                {"id": 44, "label": "hypogymnia_physodes", "translation": "Pustułka pęcherzykowata"},
                {"id": 45, "label": "lobaria_pulmonaria", "translation": "Granicznik płucnik"},
                {"id": 46, "label": "phellinus_igniarius", "translation": "Czyreń ogniowy"},
                {"id": 47, "label": "sarcosoma_globosum", "translation": "Dzbankówka kulista"},
                {"id": 48, "label": "urnula_craterium", "translation": "Urna kraterowata"},
                {"id": 49, "label": "artomyces_pyxidatus", "translation": "Świecznik rozgałęziony"},
                {"id": 50, "label": "cladonia_stellaris", "translation": "Chrobotek alpejski"},
                {"id": 51, "label": "fomes_fomentarius", "translation": "Hubiak pospolity"},
                {"id": 52, "label": "imleria_badia", "translation": "Podgrzyb brunatny"},
                {"id": 53, "label": "lycoperdon_perlatum", "translation": "Purchawka chropowata"},
                {"id": 54, "label": "phellinus_tremulae", "translation": "Czyreń osikowy"},
                {"id": 55, "label": "schizophyllum_commune", "translation": "Rozszczepka pospolita"},
                {"id": 56, "label": "verpa_bohemica", "translation": "Naparstniczka czeska"},
                {"id": 57, "label": "bjerkandera_adusta", "translation": "Szaroporka podpalana"},
                {"id": 58, "label": "clitocybe_nebularis", "translation": "Lejkówka szarawa"},
                {"id": 59, "label": "fomitopsis_betulina", "translation": "Pniarek brzozowy"},
                {"id": 60, "label": "inonotus_obliquus", "translation": "Błyskoporek podkorowy"},
                {"id": 61, "label": "macrolepiota_procera", "translation": "Czubajka kania"},
                {"id": 62, "label": "phlebia_radiata", "translation": "Żylak promienisty"},
                {"id": 63, "label": "stereum_hirsutum", "translation": "Skórnik szorstki"},
                {"id": 64, "label": "vulpicida_pinastri", "translation": "Złotlinka jaskrawa"},
                {"id": 65, "label": "boletus_edulis", "translation": "Borowik szlachetny"},
                {"id": 66, "label": "coltricia_perennis", "translation": "Stułka piaskowa"},
                {"id": 67, "label": "fomitopsis_pinicola", "translation": "Pniarek obrzeżony"},
                {"id": 68, "label": "kuehneromyces_mutabilis", "translation": "Łuskwiak zmienny"},
                {"id": 69, "label": "merulius_tremellosus", "translation": "Żylak trzęsakowaty"},
                {"id": 70, "label": "pholiota_aurivella", "translation": "Łuskwiak złotawy"},
                {"id": 71, "label": "stropharia_aeruginosa", "translation": "Pierścieniak grynszpanowy"},
                {"id": 72, "label": "xanthoria_parietina", "translation": "Złotorost ścienny"},
                {"id": 73, "label": "boletus_reticulatus", "translation": "Borowik usiatkowany"},
                {"id": 74, "label": "coprinellus_disseminatus", "translation": "Czernidłak gromadny"},
                {"id": 75, "label": "ganoderma_applanatum", "translation": "Lakownica spłaszczona"},
                {"id": 76, "label": "lactarius_deliciosus", "translation": "Mleczaj rydz"},
                {"id": 77, "label": "mutinus_ravenelii", "translation": "Mądziak malinowy"},
                {"id": 78, "label": "pholiota_squarrosa", "translation": "Łuskwiak nastroszony"},
                {"id": 79, "label": "suillus_granulatus", "translation": "Maślak ziarnisty"},
                {"id": 80, "label": "calocera_viscosa", "translation": "Pięknoróg największy"},
                {"id": 81, "label": "coprinellus_micaceus", "translation": "Czernidłak błyszczący"},
                {"id": 82, "label": "graphis_scripta", "translation": "Literak właściwy"},
                {"id": 83, "label": "lactarius_torminosus", "translation": "Mleczaj wełnianka"},
                {"id": 84, "label": "nectria_cinnabarina", "translation": "Gruzełek cynobrowy"},
                {"id": 85, "label": "physcia_adscendens", "translation": "Obrost wzniesiony"},
                {"id": 86, "label": "suillus_grevillei", "translation": "Maślak żółty"},
                {"id": 87, "label": "calycina_citrina", "translation": "Dwuzarodniczka cytrynowa"},
                {"id": 88, "label": "coprinopsis_atramentaria", "translation": "Czernidłak pospolity"},
                {"id": 89, "label": "gyromitra_esculenta", "translation": "Piestrzenica kasztanowata"},
                {"id": 90, "label": "lactarius_turpis", "translation": "Mleczaj paskudnik"},
                {"id": 91, "label": "panellus_stipticus", "translation": "Łycznik ochrowy"},
                {"id": 92, "label": "platismatia_glauca", "translation": "Płucnik modry"},
                {"id": 93, "label": "suillus_luteus", "translation": "Maślak zwyczajny"},
                {"id": 94, "label": "cantharellus_cibarius", "translation": "Pieprznik jadalny"},
                {"id": 95, "label": "coprinus_comatus", "translation": "Czernidłak kołpakowaty"},
                {"id": 96, "label": "gyromitra_gigas", "translation": "Piestrzenica olbrzymia"},
                {"id": 97, "label": "laetiporus_sulphureus", "translation": "Żółciak siarkowy"},
                {"id": 98, "label": "parmelia_sulcata", "translation": "Tarczownica bruzdkowana"},
                {"id": 99, "label": "pleurotus_ostreatus", "translation": "Boczniak ostrygowaty"},
                {"id": 100, "label": "trametes_hirsuta", "translation": "Wrośniak szorstki"}
        ]

    def get_labels(self):
        return [label["label"] for label in self.labels_data]
    
    def get_label_id_with_translation(self, label, probability):
        for label_data in self.labels_data:
            if label_data["label"] == label:
                return {
                    "id": label_data["id"],
                    "name": label_data["translation"],
                    "probability": round(probability, 2)
                }
