version: "3.9"
services:
  frontend:
    container_name: frontend-fungi-seeker
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - '4200:4200'
    networks:
      - network
    depends_on:
      - backend

  backend:
    container_name: backend-fungi-seeker
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - '8080:8080'
    networks:
      - network

    # env file contains four variables:
    # FUNGI_SEEKER_PSQL_HOST
    # FUNGI_SEEKER_PSQL_PORT
    # FUNGI_SEEKER_PSQL_USERNAME
    # FUNGI_SEEKER_PSQL_PASSWORD
    env_file:
      - .environment_variables

networks:
  network:
    driver: bridge